### ISSUE TITLE
Problem with tests

### ISSUE THREAD

**Issue by jennybc** [yangjasp/optimall#2]
I'm doing a patch release of glue, which this package depends on.

optimall had test failures during CRAN's incoming check of glue. The test failures look real to me, but I also don't think they have anything to do with glue.

In several places, optimall seems to use `expect_equal(x, y, z)` as if that checks equality of all 3 inputs, i.e. checks that x == y == z.

But that's not how `expect_equal()` works. `z` is actually being interpreted as the `tolerance` for `base::all.equal.numeric()` in all 4 cases. This probably isn't what you meant and some new setting on the CRAN incoming check machine has surfaced the problem.

Here are (some of) the places where this seems to be happening:

https://github.com/yangjasp/optimall/blob/d6e6c062074275f5b393d0208feb267bbc1cbdc7/tests/testthat/test-optimum_allocation.R#L44-L60

https://github.com/yangjasp/optimall/blob/d6e6c062074275f5b393d0208feb267bbc1cbdc7/tests/testthat/test-optimum_allocation.R#L83-L96

https://github.com/yangjasp/optimall/blob/d6e6c062074275f5b393d0208feb267bbc1cbdc7/tests/testthat/test-optimum_allocation.R#L199-L215

https://github.com/yangjasp/optimall/blob/d6e6c062074275f5b393d0208feb267bbc1cbdc7/tests/testthat/test-optimum_allocation.R#L274-L293

**Comment by jennybc** [comment]
I've just found this NEWS item which exactly describes the problem:

```
Fri, 21 Jan 2022

CHANGES IN R-devel NEW FEATURES

‘sample()’ and ‘sample.int()’ have additional sanity checks on their ‘size’ and ‘n’ arguments.

‘all.equal.numeric()’ gains a sanity check on its ‘tolerance’ argument - calling ‘all.equal(a, b, c)’ for three numeric vectors is a surprisingly common error.
```

https://developer.r-project.org/blosxom.cgi/R-devel/NEWS

**Comment by yangjasp** [comment]
Thanks for letting me know about this! It has been addressed in the latest version of the package, which was submitted to CRAN on 1/27/2022.
